// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApiTpi.Models;

public partial class Calificacione
{
    public int IdCalificacion { get; set; }

    public string Calificacion { get; set; }

    public int EdadMinima { get; set; }

    [JsonIgnore]
    public virtual ICollection<Pelicula> Peliculas { get; set; } = new List<Pelicula>();
}