// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiTpi.Models;

public partial class Cartelera
{
    public int IdCartelera { get; set; }

    public DateTime? FechaInicio { get; set; }

    public virtual ICollection<DetalleCartelera> DetalleCarteleras { get; set; } = new List<DetalleCartelera>();
}