// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiTpi.Models;

public partial class Cliente
{
    public int IdCliente { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public DateOnly FechaNacimiento { get; set; }

    public string Email { get; set; }

    public long? Telefono { get; set; }

    public int IdTipoDocumento { get; set; }

    public long Documento { get; set; }

    public int? IdUsuario { get; set; }

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();

    public virtual TiposDocumento IdTipoDocumentoNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}