// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApiTpi.Models;

public partial class DetalleCartelera
{
    public int IdDetalleCartelera { get; set; }

    public int IdCartelera { get; set; }

    public int IdPelicula { get; set; }

    [JsonIgnore]
    public virtual Cartelera IdCarteleraNavigation { get; set; }
    
    public virtual Pelicula IdPeliculaNavigation { get; set; }
}