// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiTpi.Models;

public partial class DetallesFactura
{
    public int IdDetalleFactura { get; set; }

    public int IdFactura { get; set; }

    public int IdFuncion { get; set; }

    public int? IdPromocion { get; set; }

    public decimal PrecioUnitario { get; set; }

    public int CantidadEntradas { get; set; }

    public virtual ICollection<Entrada> Entrada { get; set; } = new List<Entrada>();

    public virtual Factura IdFacturaNavigation { get; set; }

    public virtual Funcione IdFuncionNavigation { get; set; }

    public virtual Promocione IdPromocionNavigation { get; set; }
}