// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApiTpi.Models;

public partial class Empleado
{
    public int IdEmpleado { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public DateOnly FechaNacimiento { get; set; }

    public string Email { get; set; }

    public long? Telefono { get; set; }

    public int IdTipoDocumento { get; set; }

    public long Documento { get; set; }

    public DateOnly FechaAlta { get; set; }

    public int IdCargo { get; set; }

    public TimeOnly HorarioEntrada { get; set; }

    public TimeOnly HorarioSalida { get; set; }

    public int? IdUsuario { get; set; }

    [JsonIgnore]
    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();

    public virtual Cargo IdCargoNavigation { get; set; }
    [JsonIgnore]
    public virtual TiposDocumento IdTipoDocumentoNavigation { get; set; }
    [JsonIgnore]
    public virtual Usuario IdUsuarioNavigation { get; set; }
}