// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiTpi.Models;

public partial class Entrada
{
    public int IdEntrada { get; set; }

    public int IdDetalleFactura { get; set; }

    public int IdButaca { get; set; }

    public virtual Butaca IdButacaNavigation { get; set; }

    public virtual DetallesFactura IdDetalleFacturaNavigation { get; set; }
}