// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiTpi.Models;

public partial class Factura
{
    public int IdFactura { get; set; }

    public int IdCliente { get; set; }

    public int? IdEmpleado { get; set; }

    public int IdFormaPago { get; set; }

    public string Estado { get; set; }

    public DateTime Fecha { get; set; }

    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual Empleado IdEmpleadoNavigation { get; set; }

    public virtual FormasPago IdFormaPagoNavigation { get; set; }
}