// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApiTpi.Models;

public partial class Funcione
{
    public int IdFuncion { get; set; }

    public int IdSala { get; set; }

    public int IdPelicula { get; set; }

    public int IdTipoProyeccion { get; set; }

    public int IdIdioma { get; set; }

    public TimeOnly HorarioInicio { get; set; }

    public DateOnly Fecha { get; set; }

    [JsonIgnore]
    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();
    
    public virtual Idioma IdIdiomaNavigation { get; set; }
    
    public virtual Pelicula IdPeliculaNavigation { get; set; }
    
    public virtual Sala IdSalaNavigation { get; set; }
    
    public virtual TiposProyeccione IdTipoProyeccionNavigation { get; set; }
}