// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApiTpi.Models;

public partial class Pelicula
{
    public int IdPelicula { get; set; }

    public string Titulo { get; set; }

    public string Sinopsis { get; set; }

    public int IdGenero { get; set; }

    public int IdCalificacion { get; set; }

    public int IdPaisOrigen { get; set; }

    public string Productora { get; set; }

    public string Director { get; set; }

    public int Duracion { get; set; }

    public DateTime FechaEstreno { get; set; }
    public string Estado { get; set; }
    public byte[] Imagen { get; set; }

    [JsonIgnore]
    public virtual ICollection<DetalleCartelera> DetalleCarteleras { get; set; } = new List<DetalleCartelera>();
    [JsonIgnore]
    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();
    [JsonIgnore]
    public virtual Calificacione IdCalificacionNavigation { get; set; }
    [JsonIgnore]
    public virtual Genero IdGeneroNavigation { get; set; }
    [JsonIgnore]
    public virtual PaisesOrigene IdPaisOrigenNavigation { get; set; }
}