// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiTpi.Models;

public partial class Promocione
{
    public int IdPromocion { get; set; }

    public string Descripcion { get; set; }

    public decimal Descuento { get; set; }

    public DateTime FechaVigencia { get; set; }

    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();
}