// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApiTpi.Models;

public partial class TiposProyeccione
{
    public int IdTipoProyeccion { get; set; }

    public string TipoProyeccion { get; set; }

    [JsonIgnore]
    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();
}